# Generated by Django 6.0 on 2026-03-05 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhaar_image', models.ImageField(upload_to='aadhaar_images/')),
                ('live_photo', models.ImageField(upload_to='visitor_photos/')),
                ('aadhaar_face_encoding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockedVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20, unique=True)),
                ('block', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='resident_photos/')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('home', 'At Home'), ('away', 'Away'), ('dnd', 'Do Not Disturb')], default='home', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.TextField()),
                ('purpose_category', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose_risk_score', models.FloatField(default=0.0)),
                ('face_match_score', models.FloatField(default=0.0)),
                ('face_verified', models.BooleanField(default=False)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('resident_available', models.BooleanField(default=False)),
                ('resident_approved', models.BooleanField(blank=True, null=True)),
                ('purpose_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('face_failed', 'Face Verification Failed'), ('resident_unavailable', 'Resident Unavailable'), ('purpose_rejected', 'Purpose Rejected'), ('approved', 'Approved'), ('denied', 'Denied'), ('completed', 'Visit Completed'), ('expired', 'QR Expired')], default='pending', max_length=25)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr_valid_until', models.DateTimeField(blank=True, null=True)),
                ('qr_used', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='visitor_verification.resident')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitor_verification.visitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('visit_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitor_verification.visitlog')),
            ],
        ),
    ]
