# Generated by Django 6.0 on 2026-02-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
