# Generated by Django 6.0 on 2026-02-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0002_assignment_accepted_assignment_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
