# Generated by Django 6.0 on 2026-03-05 09:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('approved_purposes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['flat_number'],
            },
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_email', models.EmailField(blank=True, max_length=254)),
                ('resident_flat', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=200)),
                ('face_match_score', models.FloatField(default=0.0)),
                ('id_ocr_confidence', models.FloatField(default=0.0)),
                ('tampering_score', models.FloatField(default=0.0)),
                ('purpose_match_score', models.FloatField(default=0.0)),
                ('resident_validation', models.FloatField(default=0.0)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('overall_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('live_photo', models.TextField(blank=True)),
                ('id_photo', models.TextField(blank=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
