# Generated by Django 5.2.7 on 2025-12-17 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10, unique=True)),
                ('code_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('PERMANENT', 'Permanent')], default='ONE_TIME', max_length=20)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card_image', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('frequent_visitor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('IN', 'Entry'), ('OUT', 'Exit')], max_length=3)),
                ('verified_by_ml', models.BooleanField(default=False)),
                ('face_match_score', models.FloatField(default=0.0)),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='visitors.accesscode')),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_from', models.DateTimeField(blank=True, null=True)),
                ('scheduled_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('auto_decision', models.BooleanField(default=False)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='visitors.visitor')),
            ],
        ),
        migrations.AddField(
            model_name='accesscode',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_code', to='visitors.visitrequest'),
        ),
    ]
