# Generated by Django 6.0 on 2026-01-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='face_vector_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='face_match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='overall_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='text_risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('HIGH_RISK', 'High Risk – Manual Review')], default='PENDING', max_length=20),
        ),
    ]
