# Generated by Django 6.0 on 2026-01-02 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_face_vector_id_visitrequest_anomaly_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitrequest',
            old_name='scheduled_from',
            new_name='expected_arrival',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='request_time',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='scheduled_to',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='visitrequest',
            name='visitor',
        ),
        migrations.AddField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='purpose_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='relation_to_resident',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('friend', 'Friend'), ('service', 'Service/Delivery'), ('maintenance', 'Maintenance'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='target_flat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='target_resident_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visit_photos/%Y/%m/%d/'),
        ),
    ]
