# Generated by Django 6.0 on 2026-01-02 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_rename_scheduled_from_visitrequest_expected_arrival_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesscode',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='gateevent',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='visitrequest',
            options={'ordering': ('-request_time',)},
        ),
        migrations.RenameField(
            model_name='visitrequest',
            old_name='purpose_details',
            new_name='purpose',
        ),
        migrations.RemoveField(
            model_name='gateevent',
            name='face_match_score',
        ),
        migrations.RemoveField(
            model_name='gateevent',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='face_vector_id',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='id_card_image',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='id_card_number',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gateevent',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='face_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitrequest',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='visitors.visitor'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='code_type',
            field=models.CharField(choices=[('ONE_TIME', 'One-time'), ('TEMP', 'Temporary'), ('PERM', 'Permanent')], default='ONE_TIME', max_length=16),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='visitors.visitrequest'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gateevent',
            name='access_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='visitors.accesscode'),
        ),
        migrations.AlterField(
            model_name='gateevent',
            name='direction',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], default='IN', max_length=3),
        ),
        migrations.AlterField(
            model_name='gateevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='overall_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='relation_to_resident',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='target_flat',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='target_resident_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='text_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='visitrequest',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitor_photos/'),
        ),
    ]
